-- MySQL Script generated by MySQL Workbench
-- Wed Dec 13 07:05:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema player
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema player
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `player` DEFAULT CHARACTER SET utf8 ;
USE `player` ;

-- -----------------------------------------------------
-- Table `player`.`Race`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player`.`Race` (
  `idRace` INT NOT NULL AUTO_INCREMENT,
  `raceValue` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `player`.`Profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player`.`Profession` (
  `idProfession` INT NOT NULL AUTO_INCREMENT,
  `professionValue` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfession`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `player`.`Players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `player`.`Players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `RaceId` INT NOT NULL,
  `ProfessionId` INT NOT NULL,
  `level` INT NOT NULL,
  `birthday` DATE NOT NULL,
  `banned` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `Rase_idx` (`RaceId` ASC) VISIBLE,
  INDEX `Profession_idx` (`ProfessionId` ASC) VISIBLE,
  CONSTRAINT `Rase`
    FOREIGN KEY (`RaceId`)
    REFERENCES `player`.`Race` (`idRace`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Profession`
    FOREIGN KEY (`ProfessionId`)
    REFERENCES `player`.`Profession` (`idProfession`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
